<a href="https://colab.research.google.com/github/Muneeswaran557/Data-Analysis-Using-Python/blob/main/internship_from_pytho_analysic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Mark1 = int(input("Enter Mark 1: "))
Mark2 = int(input("Enter Mark 2: "))
Mark3 = int(input("Enter Mark 3: "))

Total = Mark1 + Mark2 + Mark3
Average = Total/3

print("Total:", Total)
print("Average:", Average)

if Average >= 50:
  print("pass")
else:
  print("fail")




In [ ]:
day2:


In [ ]:
Expenses = (100, 250, 300, 150)

Total = sum(Expenses)

print( "Expenses:", Expenses)
print( " Total Expenses:", Total)



In [ ]:
Day 3


In [ ]:
import numpy as np
marks = np.array([76,80,90,67])
average = np.mean(marks)
print(average)

78.25


In [ ]:
import numpy as np
salary=np.array([10000,20000,30000,40000,60000])
med=np.median(salary)
print(med)

30000.0


In [ ]:
import numpy as np
arr=np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Day  4


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6,])

new_arr = arr.reshape(2,3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
scores=[80,90,78,95,88]

total=sum(scores)
average=total/len(scores)
highest=max(scores)
lowest=min(scores)

print("Total Score:",total)
print("Average Score:",average)
print("Highest Score:",highest)
print("Lowest Score:",lowest)

Total Score: 431
Average Score: 86.2
Highest Score: 95
Lowest Score: 78
